# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262c160a6540e66e1344f697d551f66c6e9dc19dac2ff45c4aad8c1a0c81c4c476bc4611cffd8f38324e8dfc729a6ac50b9db342fc94005040eb836e98bc5fab

test:
  secret_key_base: df14de1c29e709f3e96049522251bd9814ad4d9d413d901130d38c0b6af2fedc84aaf9404d65150288e2d501c83380d4d26eb8883b094c1bdecbe04852df9afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
