export const SET_ERROR = 'SET_ERROR'

export const GET_GAMES = 'GET_GAMES'
export const CREATE_GAME = 'CREATE_GAME'
export const UPDATE_GAME = 'UPDATE_GAME'
export const DESTROY_GAME = 'DESTROY_GAME'

export const GET_EVERYTHING = 'GET_EVERYTHING'

export const GET_FRIENDLY_MATCHES = 'GET_FRIENDLY_MATCHES'
export const CREATE_FRIENDLY_MATCH = 'CREATE_FRIENDLY_MATCH'
export const UPDATE_FRIENDLY_MATCH = 'UPDATE_FRIENDLY_MATCH'
export const UPDATE_FRIENDLY_MATCH_LINEUP = 'UPDATE_FRIENDLY_MATCH_LINEUP'
export const DESTROY_FRIENDLY_MATCH = 'DESTROY_FRIENDLY_MATCH'

export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const GET_TEAMS = 'GET_TEAMS'
export const CREATE_TEAM = 'CREATE_TEAM'
export const UPDATE_TEAM = 'UPDATE_TEAM'

export const GET_TOURNAMENTS = 'GET_TOURNAMENTS'
export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT'
export const UPDATE_TOURNAMENT = 'UPDATE_TOURNAMENT'
export const DESTROY_TOURNAMENT = 'DESTROY_TOURNAMENT'
export const UPDATE_TOURNAMENT_MATCH = 'UPDATE_TOURNAMENT_MATCH'
export const UPDATE_TOURNAMENT_LINEUP_LIST = 'UPDATE_TOURNAMENT_LINEUP_LIST'
export const CREATE_TOURNAMENT_LINEUP = 'CREATE_TOURNAMENT_LINEUP'
export const UPDATE_TOURNAMENT_LINEUP = 'UPDATE_TOURNAMENT_LINEUP'
export const DESTROY_TOURNAMENT_LINEUP = 'DESTROY_TOURNAMENT_LINEUP'


export const GET_USERS = 'GET_USERS'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
