export const SET_EVERYTHING = 'SET_EVERYTHING'
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS'

export const SET_ERROR = 'SET_ERROR'

export const SET_CURRENT_USER_AND_TOKEN = 'SET_CURRENT_USER_AND_TOKEN'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const RESET_CURRENT_USER_AND_TOKEN = 'RESET_CURRENT_USER_AND_TOKEN'

export const SET_USER_LIST = 'SET_USER_LIST'
export const SET_USER = 'SET_USER'

export const SET_TEAM_LIST = 'SET_TEAM_LIST'
export const ADD_TEAM = 'ADD_TEAM'
export const SET_TEAM = 'SET_TEAM'

export const SET_GAME_LIST = 'SET_GAME_LIST'
export const ADD_GAME = 'ADD_GAME'
export const SET_GAME = 'SET_GAME'
export const REMOVE_GAME = 'REMOVE_GAME'

export const SET_TOURNAMENT_LIST = 'SET_TOURNAMENT_LIST'
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT'
export const SET_TOURNAMENT = 'SET_TOURNAMENT'
export const REMOVE_TOURNAMENT = 'REMOVE_TOURNAMENT'
export const ADD_TEAM_TO_TOURNAMENT = 'ADD_TEAM_TO_TOURNAMENT'
export const REMOVE_TEAM_FROM_TOURNAMENT = 'REMOVE_TEAM_FROM_TOURNAMENT'
export const SET_TOURNAMENT_TEAM = 'SET_TOURNAMENT_TEAM'
export const SET_TOURNAMENT_MATCH = 'SET_TOURNAMENT_MATCH'

export const SET_FRIENDLY_MATCH_LIST = 'SET_FRIENDLY_MATCH_LIST'
export const ADD_FRIENDLY_MATCH = 'ADD_FRIENDLY_MATCH'
export const SET_FRIENDLY_MATCH = 'SET_FRIENDLY_MATCH'
export const REMOVE_FRIENDLY_MATCH = 'REMOVE_FRIENDLY_MATCH'
export const SET_FRIENDLY_MATCH_TEAM = 'SET_FRIENDLY_MATCH_TEAM'
